name: "Labs"
paginate: 10
paginate_path: "/page:num"

markdown: maruku
permalink: pretty
pygments: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
baseurl: 

lunr_search:
  excludes: [rss.xml, atom.xml]

url: "http://localhost:4000/"
