name: "Labs"
paginate: 10
paginate_path: "/page:num"

markdown: maruku
permalink: pretty
pygments: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
baseurl: http://europeana.github.io/Labs

lunr_search:
  excludes: [rss.xml, atom.xml]

url: "http://localhost:4000/"

prose:
    rooturl: '_posts'
    ignore:
        - _config.yml
        - CNAME
        - Gemfile
        - Gemfile.lock
        - index.html
        - /_data
        - /_includes
        - /_layouts
        - /_plugins
        - /_site
    metadata:
        _posts/gallery:
            - name: "layout"
              field:
                element: "hidden"
                value: "gallery-item"
            - name: "category"
              field:
                element: "hidden"
                value: "gallery"
            - name: "permalink"
              field:
                element: "text"
                placeholder: "gallery/"
                label: "Permalink"
            - name: "title"
              field:
                element: "text"
                label: "Title"
                placeholder: "Application Title"
            - name: "imageurl"
              field:
                element: "text"
                label: "Image URL"
                placeholder: "/img/gallery/"
            - name: "featured"
              field:
                element: "checkbox"
                label: "Featured"
            - name: "published"
              field:
                element: "checkbox"
                value: true
            - name: "tags"
              field:
                element: "multiselect"
                label: "Add tags"
                placeholder: "Choose tags"
                options:
                    - name: "API Implementation"
                      value: "API Implementation"
                    - name: "Linked Open Data"
                      value: "Linked Open Data"
                    - name: "Case Study"
                      value: "Case Study"
                    - name: "Prototype"
                      value: "Prototype"
                    - name: "Hackathon"
                      value: "Hackathon"
                    - name: "ThoughtLab"
                      value: "ThoughtLab"
                    - name: "Open Source Project"
                      value: "Open Source Project"
            - name: "links"
              field:
                element: "multiselect"
                label: "Add Links"
                alterable: true
